# Generated by Django 5.2.17 on 2026-09-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_loyalty_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='test_payment',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Тестовая оплата (без денег)'),
        ),
    ]
