# Generated by Django 5.2.17 on 2026-09-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_test_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token_version',
            field=models.PositiveIntegerField(default=0, verbose_name='Версия сессий'),
        ),
    ]
