# Generated by Django 5.2.17 on 2026-09-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_account_phone_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='loyalty_pseudonym',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Псевдоним в журнале лояльности'),
        ),
    ]
