# Generated by Django 5.2.17 on 2026-09-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_alter_onecexchange_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='onecexchange',
            name='sample',
            field=models.JSONField(blank=True, default=dict, verbose_name='Пример позиции'),
        ),
        migrations.AddField(
            model_name='onecexchange',
            name='unknown_keys',
            field=models.JSONField(blank=True, default=list, verbose_name='Поля, которые мы не читаем'),
        ),
    ]
