# Generated by Django 5.2.17 on 2026-09-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_exchange_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='onecexchange',
            name='fields_report',
            field=models.JSONField(blank=True, default=dict, verbose_name='Заполненность полей'),
        ),
    ]
