# Generated by Django 5.2.17 on 2026-10-05 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_exchange_fields_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)')),
                ('source', models.CharField(choices=[('suunto', 'Suunto'), ('coros', 'COROS'), ('garmin', 'Garmin')], db_index=True, max_length=20, verbose_name='Источник')),
                ('external_id', models.CharField(db_index=True, max_length=120, verbose_name='ID у источника')),
                ('access_token', models.TextField(verbose_name='Токен доступа')),
                ('refresh_token', models.TextField(blank=True, default='', verbose_name='Токен продления')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Токен действует до')),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Подключён')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
            ],
            options={
                'verbose_name': 'Аккаунт часов',
                'verbose_name_plural': 'Аккаунты часов',
                'db_table': 'watch_accounts',
                'ordering': ['-connected_at'],
                'indexes': [models.Index(fields=['source', 'external_id'], name='watch_accou_source_f47340_idx')],
                'unique_together': {('user_id', 'source')},
            },
        ),
    ]
