# Generated by Django 5.2.17 on 2026-10-06 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_watch_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpClient',
            fields=[
                ('source', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Источник')),
                ('client_id', models.CharField(max_length=200, verbose_name='Client ID')),
                ('client_secret', models.TextField(blank=True, default='', verbose_name='Client secret')),
                ('redirect_uri', models.CharField(max_length=300, verbose_name='Адрес возврата')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Зарегистрировано')),
            ],
            options={
                'verbose_name': 'Приложение у партнёра',
                'verbose_name_plural': 'Приложения у партнёров',
                'db_table': 'mcp_clients',
            },
        ),
    ]
