# Generated by Django 5.2.17 on 2026-09-24 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0020_checkdismissal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.CharField(choices=[('catalog', 'Каталог (товар точь-в-точь)'), ('model', 'На модели (маркетинг)')], default='catalog', max_length=16, verbose_name='Трек')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Заметка')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_batches', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Пакет фото',
                'verbose_name_plural': 'Пакеты фото',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Артикул (папка)')),
                ('track', models.CharField(default='catalog', max_length=16, verbose_name='Трек')),
                ('attach_as', models.CharField(choices=[('main', 'Главное фото'), ('gallery', 'Галерея')], default='main', max_length=8, verbose_name='Куда')),
                ('source', models.FileField(upload_to='photopipeline/source/', verbose_name='Исходник')),
                ('master', models.FileField(blank=True, upload_to='photopipeline/master/', verbose_name='Мастер (ИИ)')),
                ('webp', models.FileField(blank=True, upload_to='photopipeline/webp/', verbose_name='Витринный webp')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Обрабатывается'), ('done', 'Готово'), ('failed', 'Ошибка'), ('skipped', 'Без товара')], db_index=True, default='pending', max_length=12, verbose_name='Статус')),
                ('error', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attached_at', models.DateTimeField(blank=True, null=True, verbose_name='Прикреплено')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='productmedia.photobatch', verbose_name='Пакет')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_jobs', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Задание фото',
                'verbose_name_plural': 'Задания фото',
                'ordering': ['-created_at'],
            },
        ),
    ]
