# Generated by Django 5.2.17 on 2026-09-27 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmedia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photojob',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Попыток генерации'),
        ),
        migrations.AddField(
            model_name='photojob',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Замечание'),
        ),
        migrations.AddField(
            model_name='photojob',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Проверено'),
        ),
        migrations.AddField(
            model_name='photojob',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Проверил'),
        ),
        migrations.AddField(
            model_name='photojob',
            name='text',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Текст принта'),
        ),
        migrations.AlterField(
            model_name='photojob',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Генерируется'), ('review', 'На проверке'), ('done', 'На витрине'), ('rejected', 'Отклонено'), ('failed', 'Ошибка'), ('skipped', 'Без товара')], db_index=True, default='pending', max_length=12, verbose_name='Статус'),
        ),
    ]
