# Generated by Django 5.2.17 on 2026-09-27 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmedia', '0002_photojob_attempts_photojob_note_photojob_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='photojob',
            name='usage',
            field=models.JSONField(blank=True, null=True, verbose_name='Расход токенов'),
        ),
        migrations.CreateModel(
            name='PhotoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(db_index=True, max_length=64, verbose_name='Артикул (папка)')),
                ('image', models.FileField(upload_to='photopipeline/detail/', verbose_name='Крупный план')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='productmedia.photobatch', verbose_name='Пакет')),
            ],
            options={
                'verbose_name': 'Крупный план принта',
                'verbose_name_plural': 'Крупные планы принтов',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('catalog', 'Каталог (товар точь-в-точь)'), ('model', 'На модели (маркетинг)')], db_index=True, max_length=16, verbose_name='Трек')),
                ('text', models.TextField(verbose_name='Текст промта')),
                ('comment', models.CharField(blank=True, default='', max_length=200, verbose_name='Что поменяли')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_prompts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Версия промта',
                'verbose_name_plural': 'Версии промтов',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='photojob',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='productmedia.photoprompt', verbose_name='Версия промта'),
        ),
    ]
