# Generated by Django 5.2.17 on 2026-09-27 16:16

import common.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmedia', '0005_delete_photo_test_runs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photodetail',
            name='image',
            field=models.FileField(storage=common.media.private_storage, upload_to='photopipeline/detail/', verbose_name='Крупный план'),
        ),
        migrations.AlterField(
            model_name='photojob',
            name='master',
            field=models.FileField(blank=True, storage=common.media.private_storage, upload_to='photopipeline/master/', verbose_name='Мастер (ИИ)'),
        ),
        migrations.AlterField(
            model_name='photojob',
            name='source',
            field=models.FileField(storage=common.media.private_storage, upload_to='photopipeline/source/', verbose_name='Исходник'),
        ),
        migrations.AlterField(
            model_name='photojob',
            name='webp',
            field=models.FileField(blank=True, storage=common.media.private_storage, upload_to='photopipeline/webp/', verbose_name='Витринный webp'),
        ),
    ]
