# Generated by Django 5.2.17 on 2026-10-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productmedia', '0006_private_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photojob',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Генерируется'), ('review', 'На проверке'), ('done', 'На витрине'), ('marketing', 'В маркетинге'), ('rejected', 'Отклонено'), ('failed', 'Ошибка'), ('skipped', 'Без товара')], db_index=True, default='pending', max_length=12, verbose_name='Статус'),
        ),
    ]
