# Generated by Django 5.2.17 on 2026-09-10 14:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_onec_number_order_onec_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines', models.JSONField(default=list, verbose_name='Позиции чека')),
                ('amount_kop', models.PositiveIntegerField(verbose_name='Сумма, коп.')),
                ('points_returned', models.IntegerField(default=0, verbose_name='Возвращено баллов')),
                ('points_revoked', models.IntegerField(default=0, verbose_name='Снято начисленных баллов')),
                ('refund_id', models.CharField(blank=True, default='', max_length=80, verbose_name='ID возврата в ЮKassa')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('done', 'Проведён'), ('failed', 'Не прошёл')], default='pending', max_length=10, verbose_name='Статус')),
                ('error', models.CharField(blank=True, default='', max_length=300, verbose_name='Ошибка')),
                ('created_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Кто оформил')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
                'db_table': 'store_order_returns',
                'ordering': ['-created_at'],
            },
        ),
    ]
