# Generated by Django 5.2.17 on 2026-09-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Курьер и время'),
        ),
    ]
