# Generated by Django 5.2.17 on 2026-09-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_courier_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Тестовый заказ'),
        ),
    ]
