# Generated by Django 5.2.17 on 2026-10-06 08:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_shippingoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=40, verbose_name='Покупатель (ID)')),
                ('lines', models.JSONField(default=list, verbose_name='Вещи и причины')),
                ('method', models.CharField(choices=[('store', 'Принесёт в магазин'), ('parcel', 'Отправит посылкой за свой счёт')], default='store', max_length=10, verbose_name='Как сдаёт')),
                ('status', models.CharField(choices=[('awaiting', 'Ждём товар'), ('received', 'Товар получен — на проверке'), ('approved', 'Одобрена — деньги возвращаются'), ('rejected', 'Отказ'), ('canceled', 'Отменена покупателем'), ('expired', 'Истекла — товар не сдан')], db_index=True, default='awaiting', max_length=10, verbose_name='Статус')),
                ('defect_claimed', models.BooleanField(default=False, verbose_name='Покупатель заявил брак')),
                ('defect_confirmed', models.BooleanField(blank=True, help_text='Да — компенсируем и расходы покупателя на доставку до магазина.', null=True, verbose_name='Брак подтверждён осмотром')),
                ('customer_shipping_kop', models.PositiveIntegerField(default=0, help_text='По квитанции. Выплачиваются, только если брак подтверждён.', verbose_name='Расходы покупателя на доставку, коп.')),
                ('shipping_paid', models.BooleanField(default=False, verbose_name='Компенсация доставки выплачена')),
                ('decision_note', models.CharField(blank=True, default='', help_text='Покупатель увидит этот текст. При отказе — обязательно.', max_length=500, verbose_name='Решение / причина отказа')),
                ('bring_until', models.DateTimeField(verbose_name='Сдать товар до')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Товар получен')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Решение')),
                ('decided_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Кто решил')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order', verbose_name='Заказ')),
                ('order_return', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='orders.orderreturn', verbose_name='Возврат денег')),
            ],
            options={
                'verbose_name': 'Заявка на возврат',
                'verbose_name_plural': 'Заявки на возврат',
                'db_table': 'store_return_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
