# Generated by Django 5.2.17 on 2026-10-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оплачен'),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.JSONField(blank=True, default=dict, verbose_name='Чек оплаты (ЮKassa)'),
        ),
    ]
