# Generated by Django 5.2.17 on 2026-09-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_category_parent_id_product_stock_by_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_height_cm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Типовая высота, см'),
        ),
        migrations.AddField(
            model_name='category',
            name='default_length_cm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Типовая длина, см'),
        ),
        migrations.AddField(
            model_name='category',
            name='default_weight_g',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Типовой вес, г'),
        ),
        migrations.AddField(
            model_name='category',
            name='default_width_cm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Типовая ширина, см'),
        ),
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота упаковки, см'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длина упаковки, см'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_g',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес в упаковке, г'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина упаковки, см'),
        ),
    ]
