# Generated by Django 5.2.17 on 2026-09-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_clean_empty_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='global_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Общее название (1С)'),
        ),
    ]
