# Generated by Django 5.2.17 on 2026-09-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product_global_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Витринное название'),
        ),
        migrations.AddField(
            model_name='product',
            name='display_name_override',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Витринное название вручную'),
        ),
    ]
