# Generated by Django 5.2.17 on 2026-09-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_display_name_product_display_name_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Ключ модели'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_key_override',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ключ модели вручную'),
        ),
    ]
