# Generated by Django 5.2.17 on 2026-09-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_product_model_key_product_model_key_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='global_name',
        ),
    ]
