# Generated by Django 5.2.17 on 2026-09-24 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_remove_product_global_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(db_index=True, max_length=40, verbose_name='Проверка')),
                ('key', models.CharField(max_length=200, verbose_name='Ключ замечания')),
                ('fingerprint', models.CharField(max_length=40, verbose_name='Отпечаток данных')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий')),
                ('actor', models.CharField(blank=True, default='', max_length=150, verbose_name='Кто закрыл')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда')),
            ],
            options={
                'verbose_name': 'Закрытое замечание',
                'verbose_name_plural': 'Закрытые замечания',
                'db_table': 'catalog_check_dismissals',
                'ordering': ['-created_at'],
                'unique_together': {('check_id', 'key', 'fingerprint')},
            },
        ),
    ]
