# Generated by Django 5.2.17 on 2026-09-24 10:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_checkdismissal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(db_index=True, max_length=200, verbose_name='Модель (ключ)')),
                ('color', models.CharField(blank=True, default='', max_length=80, verbose_name='Цвет')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('image', models.ImageField(upload_to='uploads/photos/', verbose_name='Фото (webp)')),
                ('thumb', models.ImageField(blank=True, upload_to='uploads/photos/', verbose_name='Миниатюра (webp)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Загружено')),
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товаров',
                'db_table': 'catalog_product_photos',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['model_key', 'color', 'order'], name='catalog_pro_model_k_d32725_idx')],
            },
        ),
    ]
