# Generated by Django 5.2.17 on 2026-10-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_productphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoto',
            name='card',
            field=models.ImageField(blank=True, upload_to='uploads/photos/', verbose_name='Снимок для ленты (webp)'),
        ),
    ]
