# Generated by Django 5.2.17 on 2026-09-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('show_trails', models.BooleanField(default=False, verbose_name='Показывать «Тропы»')),
                ('show_watch', models.BooleanField(default=False, verbose_name='Показывать «Часы» (Health Connect)')),
                ('show_races', models.BooleanField(default=False, verbose_name='Показывать «Старты» (календарь забегов)')),
                ('show_league_full', models.BooleanField(default=False, verbose_name='Полная «Лига» (дивизионы, все доски и периоды)')),
                ('show_sleeping_medals', models.BooleanField(default=False, verbose_name='Показывать «спящие» медали (без критерия)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Флаги приложения',
                'verbose_name_plural': 'Флаги приложения',
                'db_table': 'app_config',
            },
        ),
    ]
