# Generated by Django 5.2.17 on 2026-09-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Ключ')),
                ('title', models.CharField(max_length=80, verbose_name='Направление')),
                ('enabled', models.BooleanField(default=False, verbose_name='Показывать в приложении')),
                ('stage', models.CharField(choices=[('not_started', 'Не начато'), ('draft', 'Черновик'), ('beta', 'Бета — не проверено вживую'), ('waiting_content', 'Готово технически, ждёт контент'), ('waiting_owner', 'Ждёт решения владельца'), ('collapsed', 'Свёрнуто до запуска'), ('ready', 'Готово — можно включать')], default='draft', max_length=20, verbose_name='Этап')),
                ('summary', models.TextField(blank=True, verbose_name='Что это')),
                ('done', models.TextField(blank=True, verbose_name='Что сделано')),
                ('todo', models.TextField(blank=True, verbose_name='Что осталось')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Направление приложения',
                'verbose_name_plural': 'Флаги приложения',
                'db_table': 'feature_flag',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='AppConfig',
        ),
    ]
