# Generated by Django 5.2.17 on 2026-09-18 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=100, verbose_name='Список')),
                ('hidden', models.JSONField(blank=True, default=list, verbose_name='Скрытые столбцы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_columns', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Столбцы списка',
                'verbose_name_plural': 'Столбцы списков',
                'db_table': 'admin_columns',
                'unique_together': {('user', 'model_label')},
            },
        ),
    ]
