# Generated by Django 5.2.17 on 2026-09-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_loyalty_code'),
        ('legal', '0005_legaldocument_contacts_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentClient',
            fields=[
            ],
            options={
                'verbose_name': 'Согласия клиента',
                'verbose_name_plural': 'Согласия клиентов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.account',),
        ),
    ]
