# Generated by Django 5.2.17 on 2026-09-16 02:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_id', models.CharField(db_index=True, max_length=40, verbose_name='Отправитель (ID)')),
                ('addressee_id', models.CharField(db_index=True, max_length=40, verbose_name='Получатель (ID)')),
                ('status', models.CharField(choices=[('pending', 'Заявка'), ('accepted', 'Друзья')], db_index=True, default='pending', max_length=12, verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Дружба',
                'verbose_name_plural': 'Дружбы',
                'db_table': 'friendships',
                'unique_together': {('requester_id', 'addressee_id')},
            },
        ),
    ]
