# Generated by Django 5.2.17 on 2026-09-16 13:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendMapPrefs',
            fields=[
                ('user_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Пользователь (ID)')),
                ('visible', models.BooleanField(default=False, verbose_name='Показывать меня друзьям')),
                ('precision', models.CharField(default='hex', max_length=8, verbose_name='Точность')),
                ('hide_until', models.DateTimeField(blank=True, null=True, verbose_name='В «Тени» до')),
                ('home_lat', models.FloatField(blank=True, null=True, verbose_name='Дом: широта')),
                ('home_lng', models.FloatField(blank=True, null=True, verbose_name='Дом: долгота')),
                ('home_hidden', models.BooleanField(default=True, verbose_name='Скрывать точку у дома')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Приватность карты друзей',
                'verbose_name_plural': 'Приватность карты друзей',
                'db_table': 'friend_map_prefs',
            },
        ),
        migrations.CreateModel(
            name='FriendPosition',
            fields=[
                ('user_id', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Пользователь (ID)')),
                ('lat', models.FloatField(verbose_name='Широта (огрублённая)')),
                ('lng', models.FloatField(verbose_name='Долгота (огрублённая)')),
                ('status', models.CharField(blank=True, default='', max_length=20, verbose_name='Статус')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Позиция на карте друзей',
                'verbose_name_plural': 'Позиции на карте друзей',
                'db_table': 'friend_positions',
            },
        ),
    ]
