# Generated by Django 5.2.17 on 2026-09-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friendmapprefs_friendposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendmapprefs',
            name='beacon_trusted',
            field=models.JSONField(blank=True, default=list, verbose_name='Доверенные («Маяк»)'),
        ),
        migrations.AddField(
            model_name='friendmapprefs',
            name='beacon_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='«Маяк» активен до'),
        ),
        migrations.AddField(
            model_name='friendposition',
            name='beacon',
            field=models.BooleanField(default=False, verbose_name='«Маяк» (точная точка)'),
        ),
        migrations.AddField(
            model_name='friendposition',
            name='exact_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Точная широта («Маяк»)'),
        ),
        migrations.AddField(
            model_name='friendposition',
            name='exact_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Точная долгота («Маяк»)'),
        ),
        migrations.AlterField(
            model_name='friendposition',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта (огрублённая)'),
        ),
        migrations.AlterField(
            model_name='friendposition',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота (огрублённая)'),
        ),
    ]
