# Generated by Django 5.2.17 on 2026-10-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalworkout',
            name='track_points',
            field=models.IntegerField(default=0, verbose_name='Точек трека'),
        ),
        migrations.AddField(
            model_name='externalworkout',
            name='trust_level',
            field=models.CharField(blank=True, choices=[('high', 'Высокая — засчитываем всё'), ('medium', 'Средняя — километры сразу, захват после разбора'), ('low', 'Низкая — не засчитываем')], default='', max_length=10, verbose_name='Достоверность'),
        ),
        migrations.AddField(
            model_name='externalworkout',
            name='trust_note',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Чего не хватило'),
        ),
        migrations.AddField(
            model_name='externalworkout',
            name='trust_score',
            field=models.IntegerField(default=0, verbose_name='Оценка достоверности'),
        ),
    ]
