# Generated by Django 5.2.17 on 2026-09-27 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_pk', models.BigIntegerField(db_index=True, verbose_name='Заказ (служебно)')),
                ('line', models.PositiveIntegerField(verbose_name='Строка')),
                ('sold_at', models.DateTimeField(db_index=True, verbose_name='Продано')),
                ('product_id', models.CharField(blank=True, default='', max_length=80, verbose_name='Товар (ID)')),
                ('article', models.CharField(blank=True, default='', max_length=80, verbose_name='Артикул')),
                ('model_key', models.CharField(blank=True, default='', max_length=200, verbose_name='Модель')),
                ('name', models.CharField(blank=True, default='', max_length=300, verbose_name='Название')),
                ('brand', models.CharField(blank=True, default='', max_length=120, verbose_name='Бренд')),
                ('category_id', models.CharField(blank=True, default='', max_length=80, verbose_name='Категория')),
                ('size', models.CharField(blank=True, default='', max_length=40, verbose_name='Размер')),
                ('color', models.CharField(blank=True, default='', max_length=80, verbose_name='Цвет')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.FloatField(default=0, verbose_name='Цена, ₽')),
                ('refunded', models.BooleanField(default=False, verbose_name='Возвращено')),
            ],
            options={
                'verbose_name': 'Продажа (статистика)',
                'verbose_name_plural': 'Продажи (статистика, без покупателя)',
                'db_table': 'analytics_sale_lines',
                'constraints': [models.UniqueConstraint(fields=('order_pk', 'line'), name='sale_line_once')],
            },
        ),
    ]
