# Generated by Django 5.2.17 on 2026-09-28 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territories', '0006_clean_existing_spikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureAward',
            fields=[
                ('capture_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Захват (ID)')),
                ('user_id', models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)')),
                ('points', models.IntegerField(default=0, verbose_name='Баллов за новую землю')),
                ('awarded', models.IntegerField(default=0, verbose_name='Выплачено')),
                ('run_id', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='Пробежка (ID)')),
                ('distance_m', models.FloatField(default=0, verbose_name='Дистанция из захвата, м')),
                ('route_m', models.FloatField(default=0, verbose_name='Длина контура, м')),
                ('elapsed_s', models.IntegerField(default=0, verbose_name='Время из захвата, с')),
                ('status', models.CharField(db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Пометка')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Получен')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='Решён')),
            ],
            options={
                'verbose_name': 'Баллы за захват',
                'verbose_name_plural': 'Баллы за захваты',
                'db_table': 'territory_capture_awards',
            },
        ),
    ]
