# Generated by Django 5.2.17 on 2026-09-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_seasonclose_division_divisionmember_seasonresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='runnerprofile',
            name='track_backup',
            field=models.BooleanField(default=False, verbose_name='Резервная копия треков'),
        ),
    ]
