# Generated by Django 5.2.17 on 2026-09-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_run_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='points_capped',
            field=models.IntegerField(default=0, verbose_name='Срезано потолком, баллов'),
        ),
    ]
