# Generated by Django 5.2.17 on 2026-09-16 02:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_alter_loyaltytransaction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('category', models.CharField(choices=[('nutrition', 'Спортпитание и витамины'), ('coffee', 'Кофе'), ('gear', 'Экипировка'), ('food', 'Здоровое питание'), ('other', 'Другое')], db_index=True, default='nutrition', max_length=20, verbose_name='Категория')),
                ('emoji', models.CharField(blank=True, default='', help_text='Пока нет логотипа — эмодзи на метке, напр. 🥗 ☕ 👟', max_length=8, verbose_name='Значок (эмодзи)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Логотип (необязательно)')),
                ('city', models.CharField(blank=True, db_index=True, default='Якутск', max_length=120, verbose_name='Город')),
                ('address', models.CharField(blank=True, default='', max_length=250, verbose_name='Адрес')),
                ('description', models.CharField(blank=True, default='', help_text='Коротко: «спортивное питание», «кофе с собой»', max_length=250, verbose_name='Описание')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('points_percent', models.PositiveIntegerField(default=0, help_text='До скольких % чека можно оплатить баллами МАТА (напр. 30)', verbose_name='Оплата баллами, % от суммы')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен (показывать на карте)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Заведён')),
            ],
            options={
                'verbose_name': 'Партнёр на карте',
                'verbose_name_plural': 'Партнёры на карте (лояльность)',
                'db_table': 'loyalty_partners',
                'ordering': ['name'],
            },
        ),
    ]
