# Generated by Django 5.2.17 on 2026-09-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0004_wallet_unique_ops'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltytransaction',
            name='available_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Доступны с'),
        ),
    ]
