# Generated by Django 5.2.17 on 2026-09-29 16:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models

# Журнал loyalty_events — только добавление (ТЗ §5): кроме запрета в модели,
# менеджере и админке — триггер БД на UPDATE и DELETE. Таблица новая, данных нет —
# на проде миграция безопасна.
_TRIGGER_SQL = """
CREATE OR REPLACE FUNCTION loyalty_events_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'loyalty_events: журнал только дописывается';
END;
$$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS loyalty_events_append_only ON loyalty_events;
CREATE TRIGGER loyalty_events_append_only BEFORE UPDATE OR DELETE ON loyalty_events
    FOR EACH ROW EXECUTE PROCEDURE loyalty_events_append_only();
"""
_DROP_SQL = """
DROP TRIGGER IF EXISTS loyalty_events_append_only ON loyalty_events;
DROP FUNCTION IF EXISTS loyalty_events_append_only();
"""


def _add_trigger(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(_TRIGGER_SQL)


def _drop_trigger(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(_DROP_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0005_loyaltytransaction_available_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID события')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда (UTC)')),
                ('user_pseudonym', models.CharField(db_index=True, max_length=40, verbose_name='Псевдоним')),
                ('type', models.CharField(choices=[('accrue_purchase', 'accrue_purchase'), ('accrue_run', 'accrue_run'), ('accrue_capture', 'accrue_capture'), ('accrue_stage', 'accrue_stage'), ('accrue_referral', 'accrue_referral'), ('accrue_signup', 'accrue_signup'), ('accrue_manual', 'accrue_manual'), ('accrue_migration', 'accrue_migration'), ('hold_release', 'hold_release'), ('redeem', 'redeem'), ('redeem_return', 'redeem_return'), ('cancel', 'cancel'), ('expire', 'expire'), ('level_up', 'level_up'), ('level_down', 'level_down'), ('stoploss_on', 'stoploss_on'), ('stoploss_off', 'stoploss_off')], db_index=True, max_length=20, verbose_name='Тип')),
                ('amount', models.IntegerField(default=0, verbose_name='Сумма (со знаком)')),
                ('balance_after', models.IntegerField(default=0, verbose_name='Доступно после')),
                ('status_points_after', models.IntegerField(default=0, verbose_name='Статусные после')),
                ('level_at_event', models.PositiveSmallIntegerField(default=0, verbose_name='Уровень до')),
                ('level_after', models.PositiveSmallIntegerField(default=0, verbose_name='Уровень после')),
                ('lot_id', models.BigIntegerField(blank=True, null=True, verbose_name='Лот')),
                ('lot_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Лот сгорает')),
                ('source_ref', models.CharField(blank=True, default='', max_length=80, verbose_name='Основание')),
                ('order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма заказа')),
                ('eligible_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Допущено к списанию')),
                ('cash_part', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Денежная часть')),
                ('cogs_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Себестоимость (1С)')),
                ('partner_id', models.CharField(blank=True, default='', max_length=40, verbose_name='Партнёр')),
                ('rule_version', models.CharField(max_length=40, verbose_name='Версия правил')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Событие лояльности',
                'verbose_name_plural': 'Журнал лояльности',
                'db_table': 'loyalty_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReserve',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('reserve_rub', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Резерв, ₽')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Резерв бонусов',
                'verbose_name_plural': 'Резерв бонусов',
                'db_table': 'loyalty_reserve',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyRuleSnapshot',
            fields=[
                ('version', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Версия')),
                ('constants', models.JSONField(verbose_name='Константы')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Впервые')),
            ],
            options={
                'verbose_name': 'Версия правил лояльности',
                'verbose_name_plural': 'Версии правил лояльности',
                'db_table': 'loyalty_rule_snapshots',
            },
        ),
        migrations.CreateModel(
            name='LoyaltySetting',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Параметр')),
                ('value', models.JSONField(blank=True, help_text='Пусто — значение по ТЗ v1.', null=True, verbose_name='Значение')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Кем изменено')),
            ],
            options={
                'verbose_name': 'Настройка лояльности',
                'verbose_name_plural': 'Настройки лояльности',
                'db_table': 'loyalty_settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltySettingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=40, verbose_name='Параметр')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Было')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Стало')),
                ('changed_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Кто')),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда')),
                ('comment', models.CharField(blank=True, default='', max_length=300, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Изменение настройки лояльности',
                'verbose_name_plural': 'История настроек лояльности',
                'db_table': 'loyalty_setting_changes',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40, unique=True, verbose_name='Пользователь (ID)')),
                ('level', models.PositiveSmallIntegerField(default=0, verbose_name='Уровень')),
                ('level_until', models.DateTimeField(blank=True, null=True, verbose_name='Уровень до')),
                ('level_since', models.DateTimeField(blank=True, null=True, verbose_name='Последнее повышение')),
                ('migrated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Перенесён в v1')),
                ('legacy_balance', models.IntegerField(default=0, verbose_name='Перенесено из старого реестра')),
                ('expiry_warned_at', models.DateTimeField(blank=True, null=True, verbose_name='Предупреждён о сгорании')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Уровень участника',
                'verbose_name_plural': 'Уровни участников',
                'db_table': 'loyalty_status',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)')),
                ('amount', models.IntegerField(verbose_name='Начислено')),
                ('remaining', models.IntegerField(verbose_name='Остаток')),
                ('state', models.CharField(choices=[('held', 'Ожидает'), ('available', 'Доступен'), ('spent', 'Потрачен'), ('expired', 'Сгорел'), ('cancelled', 'Отменён')], max_length=10, verbose_name='Состояние')),
                ('source', models.CharField(max_length=40, verbose_name='Источник')),
                ('source_ref', models.CharField(blank=True, default='', max_length=80, verbose_name='Основание (заказ/пробежка/…)')),
                ('status_amount', models.IntegerField(default=0, verbose_name='В статусные')),
                ('accrued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Начислен')),
                ('available_at', models.DateTimeField(blank=True, null=True, verbose_name='Доступен с')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Сгорает')),
                ('level_at_accrual', models.PositiveSmallIntegerField(default=0, verbose_name='Уровень при начислении')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Подробности')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Лот бонусов',
                'verbose_name_plural': 'Лоты бонусов',
                'db_table': 'loyalty_lots',
                'ordering': ['expires_at', 'accrued_at', 'id'],
                'indexes': [models.Index(fields=['user_id', 'state'], name='loyalty_lot_user_state'), models.Index(fields=['state', 'expires_at'], name='loyalty_lot_state_exp'), models.Index(fields=['source', 'source_ref'], name='loyalty_lot_source_ref')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source', 'purchase')), fields=('user_id', 'source_ref'), name='loyalty_lot_one_purchase'), models.UniqueConstraint(condition=models.Q(('source', 'migration')), fields=('user_id',), name='loyalty_lot_one_migration')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)')),
                ('order_id', models.CharField(max_length=40, verbose_name='Заказ')),
                ('amount', models.IntegerField(verbose_name='Бонусов')),
                ('returned', models.IntegerField(default=0, verbose_name='Возвращено (возвраты товара)')),
                ('state', models.CharField(choices=[('blocked', 'Заблокировано'), ('spent', 'Списано'), ('released', 'Разблокировано')], default='blocked', max_length=10, verbose_name='Состояние')),
                ('level_at', models.PositiveSmallIntegerField(default=0, verbose_name='Уровень при оформлении')),
                ('eligible_kop', models.BigIntegerField(default=0, verbose_name='Допущено к списанию, коп.')),
                ('ceiling', models.FloatField(default=0, verbose_name='Потолок, доля')),
                ('unit_eligible_kop', models.JSONField(blank=True, default=list, verbose_name='Допущено по единицам, коп.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Списание на заказ',
                'verbose_name_plural': 'Списания на заказы',
                'db_table': 'loyalty_redemptions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'order_id'), name='loyalty_redemption_one_per_order')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyRedemptionPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Бонусов')),
                ('returned', models.IntegerField(default=0, verbose_name='Возвращено')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='loyalty.loyaltylot', verbose_name='Лот')),
                ('redemption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='loyalty.loyaltyredemption', verbose_name='Списание')),
            ],
            options={
                'verbose_name': 'Списание из лота',
                'verbose_name_plural': 'Списания из лотов',
                'db_table': 'loyalty_redemption_parts',
            },
        ),
        migrations.RunPython(_add_trigger, _drop_trigger),
    ]
