# Generated by Django 5.2.17 on 2026-10-06 03:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0006_loyalty_v1'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40, unique=True, verbose_name='Приглашённый (ID)')),
                ('inviter_id', models.CharField(db_index=True, max_length=40, verbose_name='Пригласил (ID)')),
                ('code', models.CharField(max_length=12, verbose_name='Код')),
                ('status', models.CharField(choices=[('bound', 'Привязан'), ('rewarded', 'Бонус начислен'), ('capped', 'Лимит месяца'), ('rejected', 'Отклонено')], db_index=True, default='bound', max_length=10, verbose_name='Статус')),
                ('lot_id', models.BigIntegerField(blank=True, null=True, verbose_name='Лот бонуса')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='Пометка')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Привязан')),
                ('rewarded_at', models.DateTimeField(blank=True, null=True, verbose_name='Решён')),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
                'db_table': 'loyalty_referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40, unique=True, verbose_name='Пользователь (ID)')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='Код приглашения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Выдан')),
            ],
            options={
                'verbose_name': 'Код приглашения',
                'verbose_name_plural': 'Коды приглашения',
                'db_table': 'loyalty_referral_codes',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyStageClose',
            fields=[
                ('month', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Месяц')),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Закрыт')),
                ('winners', models.JSONField(blank=True, default=list, verbose_name='Победители')),
            ],
            options={
                'verbose_name': 'Закрытие этапа',
                'verbose_name_plural': 'Закрытия этапов',
                'db_table': 'loyalty_stage_closes',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=40, verbose_name='Пользователь (ID)')),
                ('kind', models.CharField(choices=[('run', 'Пробежка'), ('capture', 'Захват'), ('stage', 'Этап')], max_length=10, verbose_name='Событие')),
                ('ref', models.CharField(max_length=80, verbose_name='Основание (забег/захват/этап)')),
                ('source', models.CharField(blank=True, default='', max_length=20, verbose_name='Источник (app / импорт)')),
                ('run_ref', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Пробежка захвата')),
                ('status', models.CharField(choices=[('granted', 'Начислено'), ('capped', 'Лимит месяца'), ('day_limit', 'Не первая за день'), ('duplicate', 'Дубль'), ('ineligible', 'Не прошла условия'), ('suspicious', 'На проверке'), ('flagged', 'Забег помечен'), ('waiting', 'Ждёт пробежку'), ('rejected', 'Отклонено')], db_index=True, max_length=12, verbose_name='Решение')),
                ('amount', models.IntegerField(default=0, verbose_name='Начислено бонусов')),
                ('lot_id', models.BigIntegerField(blank=True, null=True, verbose_name='Лот')),
                ('month', models.CharField(db_index=True, max_length=7, verbose_name='Месяц')),
                ('day', models.DateField(blank=True, null=True, verbose_name='День (якут.)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('distance_m', models.FloatField(default=0, verbose_name='Дистанция для проверки, м')),
                ('duration_s', models.IntegerField(default=0, verbose_name='Время для проверки, с')),
                ('validated_by', models.CharField(blank=True, default='', max_length=10, verbose_name='Проверено по')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='Причина')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Подробности')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Разобрано')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=150, verbose_name='Кто разобрал')),
            ],
            options={
                'verbose_name': 'Бонус за активность',
                'verbose_name_plural': 'Бонусы за активность',
                'db_table': 'loyalty_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'month', 'status'], name='loyalty_act_month'), models.Index(fields=['user_id', 'kind', 'day'], name='loyalty_act_day')],
                'constraints': [models.UniqueConstraint(fields=('user_id', 'kind', 'ref'), name='loyalty_act_one_per_event')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPhoneGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='Ключ телефона (HMAC)')),
                ('kind', models.CharField(choices=[('signup', 'Бонус за регистрацию'), ('referral', 'Бонус за приглашение этого телефона')], max_length=10, verbose_name='Бонус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда')),
            ],
            options={
                'verbose_name': 'Разовый бонус телефона',
                'verbose_name_plural': 'Разовые бонусы телефонов',
                'db_table': 'loyalty_phone_grants',
                'constraints': [models.UniqueConstraint(fields=('key', 'kind'), name='loyalty_phone_grant_once')],
            },
        ),
    ]
